work ready
Nikoniym/qna pull request #11
Opened 2018-07-26 16:01 UTC by Nikoniym

2018-07-26 16:09 UTC, Nikoniym commented on app/controllers/application_controller.rb
> +    redirect_to root_url, alert: exception.message
Хотел использовать request.referrer вместо root_url, но в тестах request.referrer не поддерживается.
Как реализовать переход на туже страницу, откуда был запрос?

2018-07-27 07:51 UTC, vkurennov requested changes

2018-07-27 07:51 UTC, vkurennov commented on app/controllers/application_controller.rb
> +    redirect_to root_url, alert: exception.message
Тесты поддерживают реферер, но он там пустой просто. Можно его "застабить" (эта тема будет дальше по курсу), вот пример: https://stackoverflow.com/questions/12591763/how-do-i-set-a-request-referrer-inside-my-rspec

2018-07-27 07:51 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
Сделай обработку ошибки авторизации для всех типов запросов (html, js, json). для js и json можно возвращать 403 статус (forbidden), на клиенте его перехватывать и выводить сообщение

2018-07-27 07:51 UTC, vkurennov commented on app/models/ability.rb
> +    can :changes, [Question, Answer], { user: user }
Проверку лучше делать по user_id, чтобы не грузить лишнюю ассоциацию

2018-07-27 07:51 UTC, vkurennov commented on app/models/ability.rb
> +      !user.author_of?(resource)
У cancel_vote другое правило должно быть: удалить голос может только тот, кто его создал

2018-07-27 15:44 UTC, Nikoniym commented on app/models/ability.rb
> +    # can :vote, Valuable
Обнаружил баг в cancan 
При использовании conserns к примеру в строке can :like, Valuable do |resource| все условия написанные дальше не буду учитываться при работе в браузере, но в тестах все проходит. Может я что то не так сделал?
Поэтому все ниже описанное будет равноценно этим закоментированным строкам для работы в браузере.

2018-07-27 15:44 UTC, Nikoniym commented on app/models/ability.rb
> +    can :like, Valuable do |resource|
тоже самое если написать вместо Valuable [Question, Answer]

2018-07-27 15:44 UTC, Nikoniym commented on spec/models/ability_spec.rb
> +    end
Вот в тестах все учитывается, в development нет

2018-07-27 15:54 UTC, Nikoniym commented on app/assets/javascripts/ajax_requst.coffee
> +      $('.flash').html(message)
Обработчик на стороне клиента, правильно?

2018-07-27 15:54 UTC, Nikoniym commented on app/models/ability.rb
> +    can :new_comment, Commentable
Комментарий по логике после следующего.
Если написать 
can :new_comment, [Question, Answer] do |resourse|
  false
end
Все равно будет проходить.

2018-07-28 09:07 UTC, vkurennov requested changes

2018-07-28 09:07 UTC, vkurennov commented on app/assets/javascripts/ajax_requst.coffee
> +      $('.flash').html(message)
да, верно

2018-07-28 09:07 UTC, vkurennov commented on app/controllers/application_controller.rb
> +      format.json { head :forbidden, content_type: 'text/html' }
Запрос приходит в json/js, зачем менять content_type, тем более, что ответ все равно пустой? Оставляй тот же content_type и никогда не меняй его без необходимости и когда ты конкретно знаешь, зачем это делаешь

2018-07-28 09:07 UTC, vkurennov commented on app/models/ability.rb
> +    # can :vote, Valuable
Там важен порядок загрузки и наименования переменных. В принципе, в консерне ты всегда можешь в явном виде вызвать `authorize!` в экшене с нужными параметрами.

2018-07-28 09:07 UTC, vkurennov commented on app/models/ability.rb
> +    can :new_comment, Commentable
это зависит от того, как ты вызваешь авторизацию и что туда передаешь. Ну и нужно передавать объект, чтобы блок отрабатывал, если в can? или authorize! передать класс, то все условия игнорируются.

2018-07-28 09:07 UTC, vkurennov commented on app/models/ability.rb
> +    can :dislike, Valuable do |resource|
У тебя нет модели Valuble, поэтому правила и не работают. Тут нужны названия тех моделей, с которыми реально происходят действия.

2018-07-30 16:28 UTC, vkurennov approved these changes

2018-07-30 16:28 UTC, vkurennov commented on app/models/ability.rb
> +    can :vote, [Answer, Question] do |resource|
Для отмены голоса другое правило: как раз отменить его может только тот, кто его дал

2018-07-31 16:20 UTC, merged