Part 15
Nikoniym/qna pull request #13
Opened 2018-08-03 16:42 UTC by Nikoniym

2018-08-03 16:48 UTC, Nikoniym commented on app/controllers/api/v1/base_controller.rb
> +  skip_authorization_check
Оставил такой вариант, так как создать Question получается только если пользователь зашел на сайт под своим логином и паролем. А здесь я так понимаю будет другое приложение получать доступ к данным и иметь возможность создавать вопросы и ответы при это получать доступ через doorkeep, а не через форму входа на сайт. Правильно?

2018-08-04 11:15 UTC, vkurennov requested changes

2018-08-04 11:15 UTC, vkurennov commented on app/controllers/api/v1/base_controller.rb
> +  skip_authorization_check
Не правильно. Авторизация должна работать вне зависимости от того, как пользователь совершает действие - через API  или через обычный контроллер. Doorkeeper  решает задачу **аутентификации**, т.е. то, что в обычной версии делает devise. Авторизация - это определение, может ли юзер делать то или иное действие и этим у нас занимается CanCanCan. И правила должны быть универсальными.
Но тут есть нюанс: CanCanCan использует метод `current_user`, чтобы передать залогиненного пользователя в Ability-класс. Но при обращении через API этот метод вернет nil, т.к. юзер у нас возвращается через `current_resource_owner`. Нужно "научить" CanCanCan работать с этим методом.

2018-08-06 07:26 UTC, vkurennov approved these changes

2018-08-06 13:34 UTC, merged