Part 9
Nikoniym/qna pull request #7
Opened 2018-06-03 23:04 UTC by Nikoniym

2018-06-04 02:12 UTC, Nikoniym commented on db/schema.rb
> +  create_table "rating_users", force: :cascade do |t|
В первоначальном [варианте](https://github.com/Nikoniym/qna/pull/7/commits/d13304f1dd6325d127ec03e3d5fb6aa6455eb898) была только, таблица raitings и в ней user. Переделал для того чтобы было меньше запросов к базе при отображении show и работе с json, так как в raiting есть rating_count.

2018-06-04 02:12 UTC, Nikoniym commented on app/controllers/concerns/valued.rb
> +    if !current_user.author_of?(@resource) && (@resource.set_dislike?(current_user) || @resource.set_like?(current_user))
Наверное это как и два высше условия тоже лучше было вынести в модель?

2018-06-04 02:12 UTC, Nikoniym commented on app/models/concerns/valuable.rb
> +    Rating.create(ratingable: self)
Создаю так, потому что через связь has_one, при условии что объект еще не создан, возвращается nil и к нему create не применить.

Не рабочий пример:
rating.create()

2018-06-04 08:00 UTC, vkurennov requested changes

2018-06-04 08:00 UTC, vkurennov commented on app/assets/javascripts/rating.coffee
> +    object = $.parseJSON(xhr.response).object
В текущем варианте (при использовании rails-ujs) нет смысла парсить ответ, потому что в data как раз уже распарсенный json приходит

2018-06-04 08:00 UTC, vkurennov commented on app/assets/javascripts/rating.coffee
> +      object = $.parseJSON(xhr.response).object
Тут тоже проще сразу использовать data

2018-06-04 08:00 UTC, vkurennov commented on app/controllers/concerns/valued.rb
> +  def put_like
Думаю, названий вроде like/dislike  вполне достаточно, все эти "put" только добавляют шума, а нагрузки не несут. Тем более, что если вдруг http-метод изменится, то название будет вводить в заблуждение.

2018-06-04 08:00 UTC, vkurennov commented on app/controllers/concerns/valued.rb
> +        format.json { render json: { object: @resource.rating, alert: "You have already put a like on this #{resource_name}" }, status: :unprocessable_entity }
Мне кажется, тут больше подойдет статус `:forbidden`, но не настаиваю, т.к. вопрос спорный.

2018-06-04 08:00 UTC, vkurennov commented on app/controllers/concerns/valued.rb
> +    if !current_user.author_of?(@resource) && (@resource.set_dislike?(current_user) || @resource.set_like?(current_user))
Да, чтобы правила были одинаковые, вне зависимости от того, как именно вызываются эти действия - через контроллер, напрямую через модель или, скажем, через API. Ну и если правила поменяются, то менять их, в случае, если они приписаны в модели, будет проще.

2018-06-04 08:00 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +    has_one :rating, as: :ratingable, dependent: :destroy
Почему has_one? Ресурс имеет множество голосов от разных пользователей. То, что один пользователь может гоолосвать один раз, не означает, что другие не могут голосовать за ресурс.

2018-06-04 08:00 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +      rating.update(rating_count: number + 1)
update должен быть в bang-версии, раз используется транзакция.

2018-06-04 08:00 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +      rating.update(rating_count: number - 1)
`update!`

2018-06-04 08:00 UTC, vkurennov commented on app/models/rating.rb
> +class Rating < ApplicationRecord
Ты явно усложнил архитектуру, нет никакого смысла вводить третью таблицу RatingUser, потому что все можно (и нужно) хранить в этой таблице: полиморфная связ с ресурсом, `belongs_to :user` и значение голоса. Раз у тебя один юзер может голосовать за ресурс один раз, то каждая строка в этой таблице и будет означать голос юзера за конкретный ресурс.

2018-06-04 08:00 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +      rating.rating_users.create!(like: true, user: user)
хранить true/false не лучшая идея. Гораздо лучше хранить +/- 1, тогда вызывав sum у рейтинга (и немного изменив архитектуру, как описано в других замечаниях), можно легко подсчитывать общий рейтинг ресурса.

2018-06-04 08:00 UTC, vkurennov commented on db/schema.rb
> +  create_table "rating_users", force: :cascade do |t|
Напрасно переделал, это как раз тот случай, когда оптимизация вредит архитуктуре. Если ты хочешь кешировать сумму голосов (хотя можно одним запросом ее получать, если изменить способ хранения голосов), то можно добавить это поле к самому ресурсу, что фактически ты и пытаешься сделать, только через доп. таблицу. В общем, как всегда, преждевременная оптимизация - зло.

2018-06-05 08:47 UTC, vkurennov requested changes

2018-06-05 08:47 UTC, vkurennov commented on app/controllers/concerns/valued.rb
> +    if @resource.like?(current_user)
Вообще-то имелось в виду, что сама проверка должна быть внутри метод set_like/set_dislike/cancel_vote, иначе это просто замена одного метода на другой, а проблема с проверкой не решается. А чтобы у тебя в контроллере была возможность по-разному отвечать, пусть методы голосования возвращают true/false, в зависимости от результата

2018-06-05 08:47 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +    ratings.present? ? ratings.pluck(:like).sum : 0
Это не тот sum, который нужен. Здесь ты используешь sum у массива, что неэффактивно, потому что загружаются данные в память и потом суммируются средствами руби, что еще и медленно. а у ассоциаций тоже есть метод sum, который делает аграгатный запрос к базе и база сразу возвращает сумму по нужному полю, причем, если ассоциаций нет, то метод вернет 0.

2018-06-05 08:47 UTC, vkurennov commented on app/controllers/concerns/valued.rb
> +    if @resource.dislike?(current_user)
Еще непонятна логика этой проверки. Метод проверяет, есть ли голос-дизлайк от пользователя. И если есть, создает снова, а если нет, то выдает ошибку. Кажется, это не совсем верное поведение.

2018-06-05 08:47 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +    ratings.where(like: 1, user: user ).present?
Пробел перед закрывающей скобокй лишний

2018-06-05 08:47 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +
Лишняя пустая строка

2018-06-05 08:47 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +  def delete_vote!(user)
Здесь тоже нужна транзакция

2018-06-05 08:47 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +    ratings.find_by(like: -1, user: user).destroy
`destroy!`

2018-06-05 08:47 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +    ratings.find_by(like: 1, user: user).destroy
`destroy!`

2018-06-05 08:47 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +  # def like
Удаляй закомментаренный код, у тебя же контроль версий, если будет нужно - вершеншься или посмотришь по истории старый код. А так незачем хранить хлам в репозитории

2018-06-05 08:47 UTC, vkurennov commented on app/models/rating_user.rb
> +class RatingUser < ApplicationRecord
Эта модель больше не используется, нужно удалить связанную с ней таблицу и  саму модель

2018-06-06 07:47 UTC, vkurennov approved these changes

2018-06-06 07:47 UTC, vkurennov commented on app/models/concerns/valuable.rb
> +    ratings.find_by(like: -1, user: user).destroy!
Кстати, тут надо применить &.destroy, т.к. find_by может и nil вернуть и тогда будет ошибка, а оператор &. вызовет метод только если возвращен не  nil, это т.н. [safe naviagation opertor](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/)

2018-06-06 07:47 UTC, vkurennov commented on spec/models/concerns/valued_spec.rb
> +    it '#set_like?(user) false' do
В тестах моделей принято каждый метод описывать в describe, например:

```
describe "#set_like?" do
  it 'returns true if user did not vote yet for the object'
  it 'returns false if user already voted for the object
end
```

и т.д. Т.е. на каждый метод - свой describe, а внутри тесты и контексты, описывающие условия и возвращаемые значения

2018-06-06 12:09 UTC, merged